global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8081']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8082']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
